//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh_BDINT 
  {
    CHMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrCh_BDINT;

typedef struct CltCh_BDINT 
  {
    struct SvrCh_BDINT *pCh;
    BDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_BDINT;

typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct CltCh_HDINT 
  {
    struct SvrCh_HDINT *pCh;
    HDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_HDINT;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_BDINT 
  {
    CMDMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_BDINT;

typedef struct CltChCmd__Bit32 
  {
    struct SvrChCmd_BDINT *pCh;
    BDINT dData;
    _Bit32 *pCmd;
  } CltChCmd__Bit32;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__Can 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Can *pCmd;
  } CltChCmd__Can;

typedef struct CltChCmd__CheckSum 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CheckSum *pCmd;
  } CltChCmd__CheckSum;

typedef struct CltChCmd__FileSys 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _FileSys *pCmd;
  } CltChCmd__FileSys;

typedef struct CltChCmd__Grafix 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Grafix *pCmd;
  } CltChCmd__Grafix;

typedef struct CltChCmd__Lse 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Lse *pCmd;
  } CltChCmd__Lse;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct CltChCmd__OSKernel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OSKernel *pCmd;
  } CltChCmd__OSKernel;

typedef struct CltChCmd__OsziLSEBackground 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OsziLSEBackground *pCmd;
  } CltChCmd__OsziLSEBackground;

typedef struct CltChCmd__StdLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _StdLib *pCmd;
  } CltChCmd__StdLib;

typedef struct CltChCmd__SysMsg 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SysMsg *pCmd;
  } CltChCmd__SysMsg;

typedef struct CltChCmd__TaskObjectControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _TaskObjectControl *pCmd;
  } CltChCmd__TaskObjectControl;

typedef struct CltChCmd_AlarmTitleLine 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    AlarmTitleLine *pCmd;
  } CltChCmd_AlarmTitleLine;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd_CriticalSection 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    CriticalSection *pCmd;
  } CltChCmd_CriticalSection;

typedef struct CltChCmd_DataManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DataManager *pCmd;
  } CltChCmd_DataManager;

typedef struct CltChCmd_DataManagerFIFO 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    DataManagerFIFO *pCmd;
  } CltChCmd_DataManagerFIFO;

typedef struct CltChCmd_DataManagerPriority 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    DataManagerPriority *pCmd;
  } CltChCmd_DataManagerPriority;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct CltChCmd_DisplaySettings 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DisplaySettings *pCmd;
  } CltChCmd_DisplaySettings;

typedef struct CltChCmd_GetBroadCastData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetBroadCastData *pCmd;
  } CltChCmd_GetBroadCastData;

typedef struct CltChCmd_GetTaskHandle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetTaskHandle *pCmd;
  } CltChCmd_GetTaskHandle;

typedef struct CltChCmd_Graphic 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Graphic *pCmd;
  } CltChCmd_Graphic;

typedef struct CltChCmd_KeyPadImagesStdTemplate 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    KeyPadImagesStdTemplate *pCmd;
  } CltChCmd_KeyPadImagesStdTemplate;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_RamRingBuffer 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamRingBuffer *pCmd;
  } CltChCmd_RamRingBuffer;

typedef struct CltChCmd_SigCLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SigCLib *pCmd;
  } CltChCmd_SigCLib;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_StringInternal 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringInternal *pCmd;
  } CltChCmd_StringInternal;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct CltChCmd_SystemLogging 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SystemLogging *pCmd;
  } CltChCmd_SystemLogging;

typedef struct CltChCmd_TCPCommunication 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPCommunication *pCmd;
  } CltChCmd_TCPCommunication;

typedef struct CltChCmd_TCPCommunicationLogFilter 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPCommunicationLogFilter *pCmd;
  } CltChCmd_TCPCommunicationLogFilter;

typedef struct SvrCh__IMA 
  {
    CHMETH *pMeth;
    _IMA dData;
    SVRDSC *pDsc;
  } SvrCh__IMA;

typedef struct SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication 
  {
    CHMETH *pMeth;
    t_e_ConnectionType dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication;

typedef struct SvrCh_t_e_ExportState_PTofCls_TCPCommunicationLogViewer 
  {
    CHMETH *pMeth;
    t_e_ExportState dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_ExportState_PTofCls_TCPCommunicationLogViewer;

typedef struct SvrCh_TIME_LSL 
  {
    CHMETH *pMeth;
    TIME_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_TIME_LSL;

typedef struct SvrChCmd__FSM_TCP_USER 
  {
    CMDMETH *pMeth;
    _FSM_TCP_USER dData;
    SVRDSC *pDsc;
  } SvrChCmd__FSM_TCP_USER;

typedef struct SvrChCmd_DATE_LSL 
  {
    CMDMETH *pMeth;
    DATE_LSL dData;
    SVRDSC *pDsc;
  } SvrChCmd_DATE_LSL;

